
services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username_user
      POSTGRES_PASSWORD: la_la_la
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network

volumes:
  pg-data:

networks:
  pg-network:


