"""Create longer len Post class

Revision ID: 3efa2f34146f
Revises: 461cb9ea9d4b
Create Date: 2025-01-13 14:39:56.651548

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3efa2f34146f"
down_revision = "461cb9ea9d4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
