"""Create Post class Initial mig

Revision ID: 461cb9ea9d4b
Revises: 
Create Date: 2025-01-13 13:59:35.575030

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "461cb9ea9d4b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    # ### end Alembic commands ###
