"""Create class User

Revision ID: 52be54aeef83
Revises: 9e21dd7700cc
Create Date: 2025-01-14 16:42:55.393619

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52be54aeef83"
down_revision = "9e21dd7700cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_author", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
