"""Create Counter and func for this

Revision ID: 9e21dd7700cc
Revises: 3efa2f34146f
Create Date: 2025-01-13 21:12:49.365080

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e21dd7700cc"
down_revision = "3efa2f34146f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "view_count",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["view_count"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("view_count")
    # ### end Alembic commands ###
